[tool.poetry]
name = "PyGIS Blog-QUARTO"
version = "0.1.0"
description = "Qui riproduco in Python alcune delle analisi di dati che ho affrontato nei miei articoli e non solo!"
authors = ["MaxDragonheart <massimilianomoraca@gmail.com>"]
readme = "README.md"
packages = [{include = "pygisblog_quarto"}]

[tool.poetry.dependencies]
python = "^3.8"
shapely = "^1.8.5.post1"
geopandas = "^0.12.1"
rasterio = "^1.3.4"
xarray-spatial = "^0.3.5"
rioxarray = "^0.13.1"
contextily = "^1.2.0"
Rtree = "^1.0.1"
openpyxl = "^3.0.10"
jupyter = "^1.0.0"
folium = "^0.13.0"
matplotlib = "^3.6.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
